# Generated by Django 5.1 on 2024-10-30 19:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_alter_client_owner_name'),
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_of_housing', models.CharField(choices=[('Aluguel', 'Aluguel'), ('Venda', 'Venda')], max_length=7)),
                ('address', models.CharField(max_length=255)),
                ('owner_name', models.CharField(max_length=255)),
                ('client_name', models.CharField(max_length=255)),
                ('about_the_property', models.CharField(max_length=255)),
                ('rental_value', models.PositiveIntegerField()),
                ('tenant_present', models.BooleanField()),
                ('readjustment_date', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.contract')),
            ],
            options={
                'ordering': ['address'],
            },
        ),
    ]
