# Generated by Django 5.1 on 2024-10-30 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_owner_name'),
        ('contracts', '0001_initial'),
        ('real_estate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestate',
            name='client',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='contract',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.contract'),
        ),
    ]
