# Generated by Django 5.1 on 2024-10-30 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0001_initial'),
        ('real_estate', '0002_alter_realestate_client_alter_realestate_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='real_estate', to='owners.owner'),
        ),
    ]
