# Generated by Django 5.1 on 2024-11-05 20:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('owners', '0001_initial'),
        ('real_estate', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_category', models.CharField(choices=[('Manutenção', 'Manutenção'), ('Reforma', 'Reforma'), ('Pintura', 'Pintura'), ('Elétrica', 'Elétrica'), ('Hidráulica', 'Hidráulica'), ('Limpeza', 'Limpeza'), ('Jardinagem', 'Jardinagem'), ('Segurança', 'Segurança'), ('Climatização', 'Climatização'), ('Outro', 'Outro')], default='Outro', max_length=13)),
                ('service_provided', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('Pago', 'Pago'), ('Pendente', 'Pendente'), ('Atrasado', 'Atrasado')], default='Pendente', max_length=8)),
                ('date_paid', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_order_owner', to='owners.owner')),
                ('real_estate', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_order_real_estate', to='real_estate.realestate')),
            ],
        ),
    ]
