# Generated by Django 5.1 on 2024-10-28 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_orders', '0002_serviceorder_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='service_title',
            field=models.CharField(default='def', max_length=100),
            preserve_default=False,
        ),
    ]
