# Generated by Django 5.1 on 2024-10-28 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_orders', '0003_serviceorder_service_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceorder',
            name='service_title',
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='service_category',
            field=models.CharField(choices=[('Manutenção', 'Manutenção'), ('Reforma', 'Reforma'), ('Pintura', 'Pintura'), ('Elétrica', 'Elétrica'), ('Hidráulica', 'Hidráulica'), ('Limpeza', 'Limpeza'), ('Jardinagem', 'Jardinagem'), ('Segurança', 'Segurança'), ('Climatização', 'Climatização'), ('Outro', 'Outro')], default='Outro', max_length=13),
        ),
    ]
