# Generated by Django 5.1 on 2024-11-12 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_details', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankdetails',
            options={'ordering': ['bank']},
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='account',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
