# Generated by Django 5.1 on 2024-10-21 16:25

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=100)),
                ('cpf', models.CharField(blank=True, max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='CPF must have exactly 11 digits.', regex='^\\d{11}$')])),
                ('cnpj', models.CharField(blank=True, max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='CNPJ must have exactly 14 digits.', regex='^\\d{14}$')])),
                ('telephone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('last_updated_by', models.CharField(max_length=30)),
                ('type_of_sale', models.CharField(choices=[('Aluguel', 'Aluguel'), ('Venda', 'Venda')], max_length=50, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owners', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['fullname'],
            },
        ),
    ]
