# Generated by Django 5.1 on 2024-10-22 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='last_updated_by',
        ),
    ]
