# Generated by Django 5.1 on 2024-10-21 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='last_updated_by',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
