# Generated by Django 5.1 on 2024-10-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_alter_owner_last_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='last_updated_by',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
