# Generated by Django 5.1 on 2024-10-30 22:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.CharField(choices=[('Janeiro', 'Janeiro'), ('Fevereiro', 'Fevereiro'), ('Março', 'Março'), ('Abril', 'Abril'), ('Maio', 'Maio'), ('Junho', 'Junho'), ('Julho', 'Julho'), ('Agosto', 'Agosto'), ('Setembro', 'Setembro'), ('Outubro', 'Outubro'), ('Novembro', 'Novembro'), ('Dezembro', 'Dezembro')], max_length=9)),
                ('due_date', models.PositiveIntegerField()),
                ('rental_value', models.PositiveIntegerField()),
                ('status_invoice', models.CharField(choices=[('Pago', 'Pago'), ('Pendente', 'Pendente'), ('Atrasado', 'Atrasado')], default='Pendente', max_length=8)),
                ('date_it_was_paid', models.DateTimeField(blank=True, null=True)),
                ('observations', models.CharField(blank=True, max_length=255, null=True)),
                ('real_estate', models.UUIDField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client')),
            ],
        ),
    ]
