# Generated by Django 5.1 on 2024-10-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_invoices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyinvoice',
            name='day_it_was_paid',
        ),
        migrations.AddField(
            model_name='propertyinvoice',
            name='date_it_was_paid',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
