# Generated by Django 5.1 on 2024-10-30 22:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contract_belongs_to', models.CharField(max_length=100)),
                ('type_of_contract', models.CharField(choices=[('Aluguel', 'Aluguel'), ('Venda', 'Venda'), ('Não Informado', 'Não Informado')], default='Não Informado', max_length=13)),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo'), ('Pendente', 'Pendente')], default='Pendente', max_length=8)),
                ('contract_duration', models.PositiveIntegerField()),
                ('start_of_contract', models.DateTimeField()),
                ('end_of_contract', models.DateTimeField()),
                ('rental_value', models.PositiveIntegerField()),
                ('due_date', models.PositiveIntegerField()),
                ('client_id', models.UUIDField(blank=True, default=None, null=True)),
                ('owner_id', models.UUIDField(blank=True, default=None, null=True)),
                ('real_estate_id', models.UUIDField(blank=True, default=None, null=True)),
            ],
            options={
                'ordering': ['contract_belongs_to'],
            },
        ),
    ]
