# Generated by Django 5.1 on 2024-11-05 20:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('owners', '0001_initial'),
        ('real_estate', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contract_belongs_to', models.CharField(max_length=100)),
                ('type_of_contract', models.CharField(choices=[('Aluguel', 'Aluguel'), ('Venda', 'Venda'), ('Não Informado', 'Não Informado')], default='Não Informado', max_length=13)),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo'), ('Pendente', 'Pendente')], default='Pendente', max_length=8)),
                ('contract_duration', models.PositiveIntegerField()),
                ('start_of_contract', models.DateTimeField()),
                ('end_of_contract', models.DateTimeField()),
                ('rental_value', models.PositiveIntegerField()),
                ('due_date', models.PositiveIntegerField()),
                ('client', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_client', to='clients.client')),
                ('owner', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_owner', to='owners.owner')),
                ('real_estate', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_real_estate', to='real_estate.realestate')),
            ],
            options={
                'ordering': ['contract_belongs_to'],
            },
        ),
    ]
