# Generated by Django 5.1 on 2024-10-30 22:25

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=100)),
                ('cpf', models.CharField(blank=True, max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='CPF must have exactly 11 digits.', regex='^\\d{11}$')])),
                ('cnpj', models.CharField(blank=True, max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='CNPJ must have exactly 14 digits.', regex='^\\d{14}$')])),
                ('telephone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('owner_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('real_estate_id', models.UUIDField(blank=True, default=None, null=True)),
                ('contract_id', models.UUIDField(blank=True, default=None, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
