# Generated by Django 5.1 on 2024-10-23 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='owner_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
