# Generated by Django 5.1 on 2024-11-12 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['fullname']},
        ),
    ]
