# Generated by Django 5.1 on 2024-10-23 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_payment_method', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientPixDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pix_key', models.CharField(blank=True, choices=[('CPF', 'CPF'), ('CNPJ', 'CNPJ'), ('Telefone', 'Telefone'), ('Email', 'Email'), ('Chave Aleatória', 'Chave Aleatória'), ('Não Possui Pix', 'Não Possui Pix')], default='Não Possui Pix', max_length=255, null=True)),
                ('pix_type', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('client_payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pix_details', to='client_payment_method.clientpaymentmethod')),
            ],
        ),
    ]
