# Generated by Django 5.1 on 2024-10-23 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_pix_details', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientpixdetails',
            name='pix_key',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clientpixdetails',
            name='pix_type',
            field=models.CharField(blank=True, choices=[('CPF', 'CPF'), ('CNPJ', 'CNPJ'), ('Telefone', 'Telefone'), ('Email', 'Email'), ('Chave Aleatória', 'Chave Aleatória'), ('Não Possui Pix', 'Não Possui Pix')], default='Não Possui Pix', max_length=50, null=True),
        ),
    ]
