# Generated by Django 5.1 on 2024-10-23 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('owner_payment_method', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerBankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(max_length=255)),
                ('account', models.CharField(max_length=255)),
                ('agency', models.CharField(max_length=255)),
                ('owner_payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='owner_payment_method.ownerpaymentmethod')),
            ],
        ),
    ]
