# Generated by Django 5.1 on 2024-10-21 19:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('owner', '0003_alter_owner_last_updated_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerPaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sales_bonus', models.IntegerField()),
                ('profit_transfer', models.IntegerField(default=0)),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='owner.owner')),
            ],
        ),
    ]
