# Generated by Django 5.1 on 2024-10-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner_payment_method', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerpaymentmethod',
            name='profit_transfer',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ownerpaymentmethod',
            name='sales_bonus',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
