# Generated by Django 5.1 on 2024-10-21 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner_payment_method', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ownerpaymentmethod',
            old_name='owner',
            new_name='owner_id',
        ),
    ]
