# Generated by Django 5.1 on 2024-10-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner_payment_method', '0002_alter_ownerpaymentmethod_profit_transfer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerpaymentmethod',
            name='profit_transfer',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
