# Generated by Django 5.1 on 2024-10-22 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('owner_payment_method', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerPixDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pix_key', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('pix_type', models.CharField(choices=[('CPF', 'CPF'), ('CNPJ', 'CNPJ'), ('Telefone', 'Telefone'), ('Email', 'Email'), ('Chave Aleatória', 'Chave Aleatória'), ('Não Possui Pix', 'Não Possui Pix')], default='Não Possui Pix', max_length=20)),
                ('owner_payment_method_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pix_details', to='owner_payment_method.ownerpaymentmethod')),
            ],
        ),
    ]
