# Generated by Django 5.1 on 2024-10-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner_pix_details', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ownerpixdetails',
            old_name='owner_payment_method_id',
            new_name='owner_payment_method',
        ),
        migrations.AlterField(
            model_name='ownerpixdetails',
            name='pix_key',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ownerpixdetails',
            name='pix_type',
            field=models.CharField(max_length=50),
        ),
    ]
