# Generated by Django 5.1 on 2024-10-30 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_alter_client_owner_name'),
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PixDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pix_key', models.CharField(blank=True, default=None, max_length=36, null=True)),
                ('pix_type', models.CharField(choices=[('CPF', 'CPF'), ('CNPJ', 'CNPJ'), ('Telefone', 'Telefone'), ('Email', 'Email'), ('Chave Aleatória', 'Chave Aleatória'), ('Não Possui Pix', 'Não Possui Pix')], default='Não Possui Pix', max_length=15)),
                ('client', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client')),
                ('owner', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='owners.owner')),
            ],
        ),
    ]
