# Generated by Django 5.1 on 2024-11-05 20:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PixDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pix_key', models.CharField(blank=True, default=None, max_length=36, null=True)),
                ('pix_type', models.CharField(choices=[('CPF', 'CPF'), ('CNPJ', 'CNPJ'), ('Telefone', 'Telefone'), ('Email', 'Email'), ('Chave Aleatória', 'Chave Aleatória'), ('Não Possui Pix', 'Não Possui Pix')], default='Não Possui Pix', max_length=15)),
                ('client', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pix_details_client', to='clients.client')),
                ('owner', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pix_details_owner', to='owners.owner')),
            ],
        ),
    ]
