# Generated by Django 5.1 on 2024-11-12 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pix_details', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pixdetails',
            name='pix_key',
            field=models.CharField(blank=True, default=None, max_length=36, null=True, unique=True),
        ),
    ]
