# Generated by Django 5.1 on 2024-10-23 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_payment_method', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientBankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(choices=[('Banco do Brasil', 'Banco do Brasil'), ('Bradesco', 'Bradesco'), ('Caixa Econômica Federal', 'Caixa Econômica Federal'), ('Itaú', 'Itaú'), ('Santander', 'Santander'), ('BTG Pactual', 'BTG Pactual'), ('Safra', 'Safra'), ('Banco Inter', 'Banco Inter'), ('Nubank', 'Nubank'), ('C6 Bank', 'C6 Bank'), ('Banco Pan', 'Banco Pan'), ('Banrisul', 'Banrisul'), ('Banco Votorantim', 'Banco Votorantim'), ('Sicoob', 'Sicoob'), ('Sicredi', 'Sicredi'), ('Banco Original', 'Banco Original'), ('Mercado Pago', 'Mercado Pago'), ('PagSeguro', 'PagSeguro'), ('Banco BMG', 'Banco BMG'), ('Credisan', 'Credisan'), ('Banco Topázio', 'Banco Topázio'), ('Banco ABC Brasil', 'Banco ABC Brasil'), ('Banco Ribeirão Preto', 'Banco Ribeirão Preto'), ('Citibank', 'Citibank'), ('JP Morgan', 'JP Morgan'), ('Banco Modal', 'Banco Modal'), ('Banco Pine', 'Banco Pine'), ('Banco Sofisa', 'Banco Sofisa'), ('Banco Mercantil', 'Banco Mercantil'), ('Banco Cetelem', 'Banco Cetelem')], max_length=255)),
                ('account', models.CharField(max_length=255)),
                ('agency', models.CharField(max_length=255)),
                ('account_type', models.CharField(choices=[('Conta Corrente', 'Conta Corrente'), ('Conta Poupança', 'Conta Poupança'), ('Conta Salário', 'Conta Salário'), ('Conta Digital', 'Conta Digital'), ('Conta Conjunta', 'Conta Conjunta'), ('Conta de Pagamento', 'Conta de Pagamento'), ('Conta de Investimento', 'Conta de Investimento'), ('Conta Fácil', 'Conta Fácil')], max_length=255)),
                ('client_payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='client_payment_method.clientpaymentmethod')),
            ],
        ),
    ]
